### ISSUE TITLE
Closed widgets cannot be opened back on Windows 8.1

### ISSUE THREAD

**Issue by ToonLucas22** [huggle/huggle3-qt-lx#133]
With "tabs" I mean the tabs that show things such as the queue, page histories, etc. I accidentally closed the queue and some other tab and I couldn't open it back.

**Comment by benapetr** [comment]
You can, just right click header of any other tab and menu will show up

**Comment by ToonLucas22** [comment]
I right click everytime on and the menu never shows up.

**Comment by benapetr** [comment]
You can also right click on tool bar

**Comment by benapetr** [comment]
http://snag.gy/AiOya.jpg

**Comment by ToonLucas22** [comment]
Nope, right-clicking the toolbar isn't helping either

**Comment by benapetr** [comment]
Can you be more specific please in what "isn't helping" is? What does it do
when you right click it? Can you send a screenshot or something? Which
version of huggle and which OS is that?

**Comment by ToonLucas22** [comment]
It would normally open what shows in the image, but it isn't opening that. I am using Huggle 3.1.9 and Windows 8.1

**Comment by benapetr** [comment]
Ok, so you have toolbar visible but when you right click on the buttons there it doesn't show the menu?

**Comment by ToonLucas22** [comment]
Yep, it doesn't show it

**Comment by benapetr** [comment]
ok,

* shutdown huggle
* open your home folder (C:\Users\yourname\AppData\Local\Wikimedia\Huggle\Configuration
* there are two files called mainwindow_{geometry, state} you need to delete these two

start huggle again, it will look default as if you never started it since setup

**Comment by ToonLucas22** [comment]
Thanks! That fixed my issue!

**Comment by benapetr** [comment]
I am unable to reproduce this and in windows 10 it works
