### ISSUE TITLE
Fetch GENDER options of users for usage in i18n

### ISSUE THREAD

**Issue by nemobis** [huggle/huggle3-qt-lx#136]
@purodha asks for grammatical gender to be considered. That's not impossible, as the preference is exposed in the web API, but might slow down things. @purodha, you may want to try a patch yourself.
https://translatewiki.net/wiki/Thread:Support/About_Huggle:Config-display-text/ksh
https://translatewiki.net/wiki/Thread:Support/About_MediaWiki:Apihelp-titleblacklist-example-2/ksh
##

**Comment by benapetr** [comment]
How it works? What is grammatical gender, can you give me some examples of that? Thanks

**Comment by ricordisamoa** [comment]
https://translatewiki.net/wiki/Gender

**Comment by amire80** [comment]
It is simply a MediaWiki preference just like any other. It is used for formulating messages in masculine or feminine in languages that need it.

**Comment by josve05a** [comment]
Migrate this to Phabricator?

**Comment by benapetr** [comment]
I track github just as well

**Comment by benapetr** [comment]
I don't really know how to fix this problem, can someone explain to me what exactly is wanted from Huggle devs? Please no links to generic documentations, just tell me what you want me to do.

**Comment by nemobis** [comment]
Sure. The code which calls the message config-display-text should pass, as parameter, the grammatical gender of the "next [user]", fetched from the users API (https://www.mediawiki.org/wiki/API:Users ), and provide some way for the displayed translation to depend on that parameter.

Alternatively, if "next" is not a person but rather a fixed object (say, "next day"), you should specify this in the message documentation.

**Comment by benapetr** [comment]
hah, I almost feel like it's a typo, it probably shouldn't be "config-display-text" but "config-display-next" but meh...

anyway, yes this is not a person, it's an edit in this context "Display next [edit]".

**Comment by nemobis** [comment]
Petr Bena, 24/08/2017 05:45:
> anyway, yes this is not a person, it's an edit in this context "Display 
> next [edit]".

Ok thanks, done:
https://translatewiki.net/wiki/Huggle:Config-display-text/qqq

Hopefully the gender of "edit" is immutable in all languages. Sadly we 
no longer have Purodha to tell us.

**Comment by benapetr** [comment]
I actually renamed it so once translatewiki fetch last en.xml it will change
