### ISSUE TITLE
Build process failure in Linux

### ISSUE THREAD

**Issue by goetzc** [huggle/huggle3-qt-lx#157]
The build instructions provided won't work, with Huggle 3.1.18 and git master.

```
./configure --extension --qt4 #you can use --qt5 in case you have it
cd huggle_release
make
```

Tested under Linux, GCC 5.2.0, Qt 4.8.7 and Qt 5.5.1, CMake 3.3.2.

```
$ ./configure --extension --qt5                   
Options used: --extension --qt5
Checking all required packages...
Checking for cmake...                                                                               [OK]
Preparing huggle.pro file                                                                           [OK]
Executing update.sh...                                                                              [OK]
Checking if version.txt exist...                                                                    [OK]
/home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle
/home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle
/home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle
/home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle
/home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle
/home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:18 (add_subdirectory):
  The source directory

    /home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle/extension_list/extension-scoring

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:20 (add_subdirectory):
  The source directory

    /home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle/extension_list/extension-thanks

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:21 (add_subdirectory):
  The source directory

    /home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle/extension_list/enwiki

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:22 (add_subdirectory):
  The source directory

    /home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle/extension_list/mass-delivery

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:23 (add_subdirectory):
  The source directory

    /home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle/extension_list/extension-splitter-helper

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:24 (add_subdirectory):
  The source directory

    /home/goetzc/huggle/huggle3-qt-lx-3.1.18/huggle/extension_list/extension-mass-delete

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

**Comment by goetzc** [comment]
In the other hand, using this works (from the Arch Linux AUR PKGBUILD):

cmake . -DCMAKE_INSTALL_PREFIX=/usr

But only for Qt4, ```-DQT_QMAKE_EXECUTABLE=qmake-qt5``` is not detected.

**Comment by benapetr** [comment]
There is something wrong in checkout of submodules, the configure script echoed your PATH instead of actually checking them out.

This will fix the issue in your case, but I am not sure why it happened:

```
git submodule init
git submodule update
```

After these 2 commands try to delete the huggle_release folder and try

**Comment by benapetr** [comment]
I see that on some systems with git older than 1.8.4 this doesn't work, you may want to upgrade your git so that you don't have this kind of issue.

**Comment by benapetr** [comment]
I mean, there is a workaround, all you need to do is to run these 2 commands by hand from toplevel, but with newer git you don't need to.

**Comment by goetzc** [comment]
I have the latest git version 2.6.2. But this same configure error happens with the latest Huggle release 3.1.18 downloaded from https://github.com/huggle/huggle3-qt-lx/archive/3.1.18.tar.gz

So that workaround doesn't work for me.

**Comment by benapetr** [comment]
Yes that is right, downloading the gzip directly will not allow configure script to download plugins through git

**Comment by benapetr** [comment]
This probably should be somewhere in readme file, but if you download huggle using git, it should work, can you confirm that?

**Comment by goetzc** [comment]
When cloning the repo with ```git clone https://github.com/huggle/huggle3-qt-lx.git```, the configure part still doesn't work.

**Comment by benapetr** [comment]
what is the error?

**Comment by goetzc** [comment]
Oops, something was messed up. It **does** work cloning the git repo. Only the release download, which doesn't include the extensions fails the configure.

**Comment by benapetr** [comment]
Now I am completely lost.

So what is the problem then? When you git clone everything works? When you download release only non-extension build works? If so, that's kind of expected then.

**Comment by benapetr** [comment]
Extensions are each located in separate repository so if you want to build huggle with them you need to have a way to execute git submodule init. It suck and isn't anywhere in README but that's how it works. `configure` script is using git to get these extensions.

**Comment by goetzc** [comment]
Yes, exactly :)
The problem was I thought it was possible to pass --extension to configure with the release version.

**Comment by goetzc** [comment]
Would it be possible to include the instructions for the release builds too? Or is using the git master code stable?
