### ISSUE TITLE
Huggle doens't follow system's text color settings

### ISSUE THREAD

**Issue by goetzc** [huggle/huggle3-qt-lx#158]
When using a dark system theme, with light text color and dark background, Huggle doesn't follow this system settings, and as a result there is poor legibility in some parts of the program, decreasing user accessibility. 

A picture is worth a thousand words

![huggle colors](https://cloud.githubusercontent.com/assets/2220440/11023022/50f25802-863b-11e5-97b2-171c934f769c.png)

**Comment by benapetr** [comment]
Not sure if this is easily solvable, there would need to be some skins for huggle, otherwise there is no way to adjust pictures in toolbar and colors to fit the dark theme.

**Comment by benapetr** [comment]
try this: https://github.com/huggle/huggle3-qt-lx/commit/e0a46c5cde5af5f96a34567cd1cde0e0cdd37839

**Comment by goetzc** [comment]
That commit fixed most of the issues! 

The only remaining low contrast text is at the Tool bar, the ```User``` name field, ```Page``` name field; and when viewing a full page, or sometimes some diffs, "Downloading diff using a web rendering fallback, please wait..." also have low contrast. 

![huggle colors latest git](https://cloud.githubusercontent.com/assets/2220440/11069759/d3a1f4d6-87a5-11e5-9ff4-d78450614e52.png)

**Comment by benapetr** [comment]
I think that was also fixed

**Comment by goetzc** [comment]
It is in fact better for reading, but it doesn't respect the system color schema, as with a dark background and light text, it displays light background and dark text, as seen in the screenshot.

The first and seconds fields don't respect color scheme, the third does.  
![huggle](https://cloud.githubusercontent.com/assets/2220440/14771346/b4c81d44-0a4d-11e6-90b0-5640e7496390.png)
