### ISSUE TITLE
edit conflit not recognized and warn message sent

### ISSUE THREAD

**Issue by alchimista** [huggle/huggle3-qt-lx#173]
I've made a checkout and installed on fedora, and after a a revert and warn, the history tab indicated that page was reverted and user double warned by me, but still, after confirmation on wiki, the page was reverted by another user, and warned by both of us. Does huggle just waits for an edit conflict before sending the warn? It could confirm it by the rc feed itself, if the page was effectively edited by the account, only then he could send the warning.

Version 3.1.20 build: 2813 3.1.19-8-g1470638
##

**Comment by ricordisamoa** [comment]
I thought the API response made it easy to tell whether the edit was actually saved?

**Comment by alchimista** [comment]
It returns  _result="Success"_ if the edit is saved.

**Comment by benapetr** [comment]
I will check but there is API option that should prevent this, might be a MW bug as well

**Comment by methecooldude** [comment]
Very old open issue... please make a new one if this is still a problem
