### ISSUE TITLE
Users subpage updated before confirming eligibility

### ISSUE THREAD

**Issue by HarryS** [huggle/huggle3-qt-lx#177]
If anyone is bored and hasn't seen yet: https://en.wikipedia.org/wiki/Wikipedia:Huggle/Feedback#List_of_users

Basically userlistsync is running before checking other project requirements such as require-rollback are met. Flow issue is around lines 619 or so in login.cpp, should just be a bit of restructuring I think. Thanks!

**Comment by benapetr** [comment]
https://github.com/huggle/huggle3-qt-lx/commit/264de251092312db4e8f81b805ed446147e1839e
