### ISSUE TITLE
Feature request: killfile 

### ISSUE THREAD

**Issue by abartov** [huggle/huggle3-qt-lx#180]
I find I spend too much time faced with *daily* edits to extremely uninteresting (to me) articles, like kids daily TV shows, football game results, etc.  I am not interested in patrolling those pages, ever, but I *am* interested in patrolling beyond my own watchlist.

What I'd like, therefore, is a 'killfile' functionality, i.e. a blacklist of pages for which changes would not be put in the queue, and a button to add to the blacklist, so I can gradually feed those uninteresting pages to it.

Would the maintainers agree to add such a feature?  If so, would they undertake to work on it?  If not, would they accept a patch implementing it, if I wrote it?

**Comment by benapetr** [comment]
Hi yes in fact I have this in my mind for quite some time although I didn't intend this to be specific to user only. So yes this is probably one of features that should be implemented. Patches of course are always welcome :)

**Comment by benapetr** [comment]
BTW I think in your case ignoring a whole category would make more sense. That is also not supported now, but IMHO should be implemented with higher priority than what you propose.

I don't think you are eager to add thousands of pages to your personal blacklist, while you can just add 2 categories and be done with it.

**Comment by abartov** [comment]
That's true. :)

Though I'd still want a killfile too. :)

So, I cloned the repo and started reading.  I'll see if I can find time to offer a patch.

**Comment by benapetr** [comment]
I suggest you figure out how to compile whole thing as a first step ;)

**Comment by abartov** [comment]
oh, I got it to build and run without difficulty. :)
(though I don't know cmake, so don't know how to get it to build a debug version.)

**Comment by benapetr** [comment]
that depends on the platform on Windows there should be a target Debug in Visual Studio, on other platforms you can try running cmake with -DCMAKE_BUILD_TYPE=Debug option to change the default build target

**Comment by benapetr** [comment]
Please check out this docs change https://github.com/huggle/huggle3-qt-lx/commit/0d206df2789c2744f0f443e3be4d2e73c3872660 I think it's precisely what you wanted. I revamped python engine in this new version of Huggle. You will need to get a last head and compile it with python support for it to work (./configure --python --extension) then you should be able to implement this killfile feature in no time using a simple python script

**Comment by benapetr** [comment]
https://github.com/huggle/huggle3-qt-lx/blob/master/documentation/examples/killfile.py
