### ISSUE TITLE
Fedora copr project

### ISSUE THREAD

**Issue by jayvdb** [huggle/huggle3-qt-lx#186]
Create a [copr](https://fedorahosted.org/copr/wiki/UserDocs#WhatisthepurposeofCopr) repo for huggle for Fedora users.

**Comment by benapetr** [comment]
You are welcome to create it, I gave up on all these package managers long time ago. I am willing to maintain existing .deb files because we already have a cook-book for them and newly also snap files - because I like the philosophy - one package manager to rule every distro.

You can actually install snap to RedHat and derivatives (like Fedora) and then use the snapfiles to install Huggle.

**Comment by jayvdb** [comment]
fwiw, http://snapcraft.io/docs/core/install#fedora is beta for selinux, and .. it fails on Fedora 25

```
$ sudo dnf copr enable zyga/snapcore

You are about to enable a Copr repository. Please note that this
repository is not part of the main Fedora distribution, and quality
may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://fedorahosted.org/copr/wiki/UserDocs#WhatIcanbuildinCopr>, and
packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you want to continue? [y/N]: y
Repository successfully enabled.
$ sudo dnf install snapd
Fedora 25 - x86_64 - Updates                                                                                          3.1 MB/s |  10 MB     00:03    
Failed to synchronize cache for repo 'zyga-snapcore', disabling.
Failed to synchronize cache for repo 'spot-chromium', disabling.
No package snapd available.
Error: Unable to find a match.
```

I will definitely investigate snap; that looks interesting.  First step is to report that it doesnt work on Fedora 25 .. ;-)  Issue management isnt [on GitHub](https://github.com/snapcore/snapcraft).

**Comment by benapetr** [comment]
Yes, they have issue management on launchpad and I am quite surprised they claim to support so many distros, I didn't see it work anywhere to be honest, but maybe it will change. The build system is really very simple.
