### ISSUE TITLE
CMakeLists.txt error

### ISSUE THREAD

**Issue by DatGuy1** [huggle/huggle3-qt-lx#195]
`cmake : CMake Error at CMakeLists.txt:32 (add_subdirectory):
At C:\Users\Johann\Downloads\huggle3-qt-lx-patch-3\windows\release.ps1:168 char:5
+     cmake ..\..\huggle\ -G "$cmake_generator" -DPYTHON_BUILD=true -DC ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CMake Error at ..._subdirectory)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError`

I have tried reinstalling CMake, for both the 64-bit and 32-bit version. Still doesn't work.

**Comment by benapetr** [comment]
git submodule init
git submodule update

You also need to have fully working python installed, try doing it without python
