### ISSUE TITLE
Release tarballs do not include submodules

### ISSUE THREAD

**Issue by diogocp** [huggle/huggle3-qt-lx#196]
The source archives automatically generated by GitHub for releases do not include submodules. When you make a release, please create a tarball including the submodules and attach it to the release.

I'm would like to make a Gentoo package for Huggle, and without a proper tarball that I can build from, there is not much that I can do.

**Comment by benapetr** [comment]
Hi,

I think that all necessary submodules (irc libs) that are necessary for build are already part of tarball, only extensions are not.

**Comment by diogocp** [comment]
There is a libirc.zip in huggle/libs, which seems to be outdated. Using submodules for dependencies and then committing a snapshot gets you the worst of both worlds.

I suggest using [git-archive-all](https://pypi.python.org/pypi/git-archive-all/) to easily create a full release tarball.

**Comment by benapetr** [comment]
I will consider that but to be honest I find this like a "bug" in github. They should use this to generate their tarballs, instead of providing broken packages.

**Comment by Hello71** [comment]
no, they shouldn't do arbitrary (possibly large) downloads to generate archives. in some cases, like autotools, it is not possible for them to predict what commands you need to generate the distribution archive.

**Comment by benapetr** [comment]
Maybe, but if GitHub won't fix that, then I think I can close this issue, since the tarballs are generated by GitHub and you say they "shouldn't include" the submodules in them. If they shouldn't include them, then they won't be there. It's that simple.

**Comment by benapetr** [comment]
OK, so how do I stop GitHub from doing it? because it does it right now, for every release there is a link to source code package, which is broken as you say. And there doesn't seem to be a way disable that link to broken source code.

**Comment by benapetr** [comment]
So either GitHub should do it properly or leave option to disable these autogenerated source packages. I still see that as a bug on their side.

**Comment by diogocp** [comment]
You cannot disable those links, but that is beside the point. The fix for this issue is to create proper source packages and attach them to the releases, just like you do with the binary packages. See e.g. https://github.com/libcheck/check/releases.

**Comment by benapetr** [comment]
Resolved
