### ISSUE TITLE
No Release file when running apt-get update in Ubuntu Zesty

### ISSUE THREAD

**Issue by Spitfire1900** [huggle/huggle3-qt-lx#216]
After adding the Huggle repository to Ubuntu Zesty with the following commands the error "The repository 'http://ppa.launchpad.net/huggle-devs/ppa/ubuntu zesty Release' does not have a Release file" appears. I was going to add this bug to https://bugs.launchpad.net/~huggle-devs but looks like that project does not accept bugs.

```
sudo add-apt-repository ppa:huggle-devs/ppa
sudo apt-get update
```

> W: The repository 'http://ppa.launchpad.net/huggle-devs/ppa/ubuntu zesty Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch http://ppa.launchpad.net/huggle-devs/ppa/ubuntu/dists/zesty/main/binary-i386/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by benapetr** [comment]
Hi we no longer provide ppa builds they were too complex to make, you can now install huggle using snap:
```
sudo apt-get install snapd
sudo snap install huggle
```
