### ISSUE TITLE
Diff view not displaying UTF-8 properly

### ISSUE THREAD

**Issue by abartov** [huggle/huggle3-qt-lx#244]
Just installed latest Huggle binary on a new system after several months I haven't used it.  I discovered the diff view is not displaying as UTF-8, at least on Hebrew Wikipedia.  The article title is fine, as are the entries in the various toolboxes, but the main diff text is mojibaked (i.e. displayed in wrong encoding).  

See screenshot:
![huggle_utf_bug](https://user-images.githubusercontent.com/66215/30072560-9017bf62-921f-11e7-9795-269a911e6339.png)

Running Ubuntu 17.04.

**Comment by benapetr** [comment]
Is that Chromium or WebKit? (you will see that in About form).

**Comment by abartov** [comment]
QT 5.5.1 and Webkit.

**Comment by benapetr** [comment]
That is interesting, because I don't recall anything being changed there, are you sure it worked before? Did you compile it yourself before or did you use the precompiled package?

**Comment by benapetr** [comment]
The code diff of HEAD..<several months ago> is simply massive but I will have a look ;)

**Comment by abartov** [comment]
This is the snap binary.  I also tried to build it myself, with --python, but encountered issue #245 

How do I tell snap to downgrade? (It's the first time I'm encountering snap.)

**Comment by benapetr** [comment]
We don't have any snaps for older versions... But you can build Huggle without python simply by not using --python options

**Comment by benapetr** [comment]
OK since we can't confirm if it worked in past I will assume it never worked.

Can you try this:
Start huggle in debug mode, just append parameter -v to it: huggle -v
Navigate to page that is causing these problems
Open Help -> Debug -> Dump page
This will dump HTML source of currently viewed diff into a file (it should be in directory from which you started huggle).

Try to open this file in a web browser, if you see same issues as you see in huggle, problem is in HTML.

**Comment by benapetr** [comment]
I uploaded one of these here: http://petr.insw.cz/huggleDump.html

It definitely is issue with HTML, any idea what to change to make it work?

**Comment by abartov** [comment]
I probably can build without Python, but I have been looking forward to try the killfile you provided in #180 :)

**Comment by abartov** [comment]
Well, it's pretty bare HTML -- specifically, no charset specification.  Consider adding:
` <meta charset="utf-8">`

**Comment by benapetr** [comment]
then download last snap: snap install huggle --edge

**Comment by benapetr** [comment]
I added that piece of html and it's still same: http://petr.insw.cz/huggleDump.html

**Comment by abartov** [comment]
The edge build indeed does not fix it.  So it looks like the *page* encoding is fine, and the data is not.  Then I would hypothesize Huggle is losing the encoding somewhere along the way in emitting/copying this HTML buffer. :-/

**Comment by benapetr** [comment]
Yes it wasn't even supposed to fix it, but it contains support for Python which 3.2.0 is not.

**Comment by benapetr** [comment]
Hmm that is interesting though, because on Windows and my Gentoo Linux it works, I see this encoding problem only on Ubuntu.

**Comment by benapetr** [comment]
let's move this to https://phabricator.wikimedia.org/T175241

**Comment by abartov** [comment]
(for the record, this is no longer an issue with the binary I just managed to build, using qt5 and WebEngine.)
