### ISSUE TITLE
Does not build with --python

### ISSUE THREAD

**Issue by abartov** [huggle/huggle3-qt-lx#245]
On Ubuntu, with both python and python3 installed, with dev packages for both:

[ 15%] Building CXX object CMakeFiles/core.dir/pythonengine.cpp.o
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp: In function ‘PyObject* Huggle::Python::Query_IsProcessed(PyObject*, PyObject*)’:
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp:560:75: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
                 result = PyErr_NewException("EINVALIDQUERY", self, nullptr);
                                                                           ^
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp: In function ‘PyObject* Huggle::Python::Query_IsFailed(PyObject*, PyObject*)’:
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp:587:75: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
                 result = PyErr_NewException("EINVALIDQUERY", self, nullptr);
                                                                           ^
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp: In function ‘void Huggle::Python::PyInit_emb()’:
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp:675:48: error: ‘Module’ was not declared in this scope
                 Huggle_ptr = PyModule_Create2(&Module, PYTHON_API_VERSION);
                                                ^~~~~~
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp:675:74: error: ‘PyModule_Create2’ was not declared in this scope
                 Huggle_ptr = PyModule_Create2(&Module, PYTHON_API_VERSION);
                                                                          ^
CMakeFiles/core.dir/build.make:1641: recipe for target 'CMakeFiles/core.dir/pythonengine.cpp.o' failed
make[2]: *** [CMakeFiles/core.dir/pythonengine.cpp.o] Error 1

**Comment by benapetr** [comment]
I can't reproduce this, just compiled with python support.

Which OS and compiler? I need versions too. Thanks

**Comment by abartov** [comment]
I'm trying to build HEAD under Ubuntu 17.04, running gcc/g++ 6.3.0.  Python 2.7.13 and 3.5.3, with accompanying dev libraries.  Thanks.

**Comment by benapetr** [comment]
I just compiled it on ubuntu 17.04, all I needed to do was install libpython3-dev and couple of qt libraries using aptitude (I used webengine though), then

```
./configure --qt5 --web-engine --python --extension
cd huggle_release && make
```

Compiled just fine

**Comment by abartov** [comment]
I have tried this, but still get the same error.  I do have dev packages for both python 2.x and 3.x.

```
[ 40%] Building CXX object CMakeFiles/core.dir/pythonengine.cpp.o
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp: In function ‘PyObject* Huggle::Python::Query_IsProcessed(PyObject*, PyObject*)’:
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp:560:75: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
                 result = PyErr_NewException("EINVALIDQUERY", self, nullptr);
                                                                           ^
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp: In function ‘PyObject* Huggle::Python::Query_IsFailed(PyObject*, PyObject*)’:
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp:587:75: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
                 result = PyErr_NewException("EINVALIDQUERY", self, nullptr);
                                                                           ^
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp: In function ‘void Huggle::Python::PyInit_emb()’:
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp:675:48: error: ‘Module’ was not declared in this scope
                 Huggle_ptr = PyModule_Create2(&Module, PYTHON_API_VERSION);
                                                ^~~~~~
/home/abartov/dev/wiki/huggle3-qt-lx/huggle/pythonengine.cpp:675:74: error: ‘PyModule_Create2’ was not declared in this scope
                 Huggle_ptr = PyModule_Create2(&Module, PYTHON_API_VERSION);
                                                                          ^
CMakeFiles/core.dir/build.make:1636: recipe for target 'CMakeFiles/core.dir/pythonengine.cpp.o' failed
make[2]: *** [CMakeFiles/core.dir/pythonengine.cpp.o] Error 1
```

**Comment by benapetr** [comment]
Now I definitely can confirm that this works, maybe the reason for your bug is that you have both python packages? But you can download our dev VM and try there, it's based on Ubuntu and it works: https://github.com/huggle/huggle3-qt-lx/wiki/Portable-development-environment-in-Ubuntu

**Comment by abartov** [comment]
This is getting comical, but believe it or not, I just downloaded the appliance and tried to run it in VirtualBox, and it won't boot.  It starts, shows the GRUB menu, but once I pick Ubuntu (or let the 30sec interval expire), I get a black screen and nothing on it, no signs of booting Linux at all. :(

Looks like I have a Huggle curse. :-/

**Comment by abartov** [comment]
On the other hand, I've finally succeeded in building it, with --python, on my own machine (not via VirtualBox), by nuking the Huggle repo, uninstalling libpython2.7-dev, cloning the repo anew, configuring and building.
