### ISSUE TITLE
Huggle doesn't think I'm a rollbacker when using bot password 

### ISSUE THREAD

**Issue by Gaelan** [huggle/huggle3-qt-lx#251]
Hi, I'm User:Gaelan. I've been a rollbacker for a while now, but for some reason Huggle doesn't think so: "One or more projects (enwiki) do not allow you to login with edit permissions (reason: Login failed on enwiki: You don't have rollback permissions on this project.). Do you want to switch to read-only mode instead?"

I get that message when using a bot password, but "legacy" login works fine.

**Comment by benapetr** [comment]
Hi,

You need to allow Huggle to use rollback in Special:BotPasswords configuration while setting up bot password in mediawiki. It's one of permissions you need to grant it in order to work properly.

**Comment by benapetr** [comment]
Let me know if that didn't work
