### ISSUE TITLE
BotPassword users create huggle3.css in invalid username's userspace

### ISSUE THREAD

**Issue by samtarling** [huggle/huggle3-qt-lx#263]
I use [BotPasswords](https://www.mediawiki.org/wiki/Manual:Bot_passwords) to log into Huggle, and have noticed that my huggle3.css file is saved to my BotPassword login ([username]@[BotPasswordName]).

Expected behaviour would be Huggle using my actual username, and saving to a valid username's userspace.

[Example](https://en.wikipedia.org/w/index.php?title=User:There%27sNoTime@Huggle/huggle3.css&oldid=813809358)

**Comment by benapetr** [comment]
Hi,

I am fairly sure this was fixed long time ago, can you please update to last version?

**Comment by samtarling** [comment]
Derp, that'll be it
