### ISSUE TITLE
Typo in English string

### ISSUE THREAD

**Issue by fitojb** [huggle/huggle3-qt-lx#270]
https://github.com/huggle/huggle3-qt-lx/blob/e715f9ad3c256738c4fc8d5d5cdfc8c98e2dbc42/huggle/Localization/en.xml#L279

“Use HTTPS to login” should be “Use HTTPS to log in” (note the space; this is a phrasal verb whose noun form is “login”)

**Comment by kshitij98** [comment]
Hi @fitojb,  I have made the required changes.

**Comment by framawiki** [comment]
Thanks @kshitij98 and @fitojb !
