### ISSUE TITLE
Sort warning-types in menu by their description, not their internal name

### ISSUE THREAD

**Issue by ToBeFree** [huggle/huggle3-qt-lx#278]
https://phabricator.wikimedia.org/T191930

Example config excerpt from en.wikipedia.org:

warning-types:
    warning: Vandalism
    spam: Spam
    attack: Personal attacks
    test: Editing tests
    delete: Removal of content
    blank: Blanking pages
    npov: Biased content (not adhering to NPOV)
    genre: NPOV genre change
    fringe: NPOV fringe
    error: Factual errors
    bio: Inappropriate biographical content
    speedy: Removal of speedy deletion template
    afd: Removal of an AFD template
    unsor: Failing to cite a verifiable reliable source
    nor: Original research
    chat: Using talk page as forum
    mos: Manual of style

Sorting this list alphabetically by the first column, which is the current behavior, creates a weirdly sorted list in the user interface. I have always wondered about that sorting before I saw the configuration file and finally understood where it comes from.

Please sort this list by the second column.

**Comment by benapetr** [comment]
This is done intentionally so that the order can be configured, for example
```
0_spam
```
would show as first item in list you presented. Also changing the order now, would break the configuration of all people who assigned a shortcut to the item, since these shortcuts are based on index.

**Comment by ToBeFree** [comment]
Ah, all right, thank you very much. :) Yeah, I know about the shortcut problem; that's why I'm currently experimenting in my sandbox and asking people to test this before it goes live. :)

https://en.wikipedia.org/wiki/Wikipedia_talk:Huggle/Config.yaml#Improvement_under_construction_-_please_help_testing%21

**Comment by ToBeFree** [comment]
Oh no, wait. Oh no. This would require me to change seven lines per warning whenever one comes to the list!

    attack:        'Attack: Personal attack against editor'
    attack:     "Reverted edits by [[Special:Contributions/$1|$1]] ([[User talk:$1|talk]]): [[WP:NPA|personal attack]] toward another user"
    attack1: '{{subst:huggle/warn-attack-1|1=$1|2=$2}}'
    attack2: '{{subst:huggle/warn-attack-2|1=$1|2=$2}}'
    attack3: '{{subst:huggle/warn-attack-3|1=$1|2=$2}}'
    attack4: '{{subst:huggle/warn-attack-4|1=$1|2=$2}}'
    attack4im: '{{subst:huggle/warn-attack-4im|1=$1|2=$2}}'

to

    000_attack:        'Attack: Personal attack against editor'
    000_attack:     "Reverted edits by [[Special:Contributions/$1|$1]] ([[User talk:$1|talk]]): [[WP:NPA|personal attack]] toward another user"
    000_attack1: '{{subst:huggle/warn-attack-1|1=$1|2=$2}}'
    000_attack2: '{{subst:huggle/warn-attack-2|1=$1|2=$2}}'
    000_attack3: '{{subst:huggle/warn-attack-3|1=$1|2=$2}}'
    000_attack4: '{{subst:huggle/warn-attack-4|1=$1|2=$2}}'
    000_attack4im: '{{subst:huggle/warn-attack-4im|1=$1|2=$2}}'

Search+Replace is not an option here, either, because of all the false positives. Maybe with a complicated regex that is prone to errors and requires manual review afterwards. 

This is a maintenance nightmare. Could you please reconsider making the sorting column configurable?

**Comment by ToBeFree** [comment]
Another thought: If, instead of my original idea, we make this configurable, then the current behavior could be the default.

If I understand correctly, doing so would not break keyboard shortcuts until the project decides to change the sorting column. This could, for example, happen using such a setting:

    warning-sort-column: 2

(default: 1, current behavior)

**Comment by ToBeFree** [comment]
@benapetr Here's another problem: Renaming the default "warning" seems to break the default vandalism revert key "Q". How should Huggle know that "02100_warning" is the default?

Are all the problems that come with this decision really "intentional"?

**Comment by benapetr** [comment]
I take it this is already solved
