### ISSUE TITLE
Sorting of welcome-messages? Undefined?

### ISSUE THREAD

**Issue by ToBeFree** [huggle/huggle3-qt-lx#280]
How are welcome-messages sorted? I would like to have them sorted alphabetically by description. The description shown in the user interface menu should be the sorting column.

**Comment by ToBeFree** [comment]
welcome-messages:
    'Welcome: standard':                             '{{subst:Welcome}}'
    'Welcome: short':                                '{{subst:Welcome-short}}'
    'Welcome: personal (cookies)':                   '{{subst:Welcome-personal}}'
    'Welcome: graphical':                            '{{subst:Welcome-graphical}}'
    'Welcome: with menu':                            '{{subst:WelcomeMenu}}'
    'Welcome: screen':                               '{{subst:Welcome-screen}}'
    'Welcome: Unregistered':                         '{{subst:Welcome-anon}}'
    'Welcome: Unregistered: constructive':           '{{subst:Welcome-anon-constructive}}'
    'Welcome: Unregistered: unconstructive':         '{{subst:Welcome-anon-unconstructive}}'
    'Welcome: Problematic: list of rules':           '{{subst:Welcomelaws}}'
    'Welcome: Problematic: first article':           '{{subst:First article}}'
    'Welcome: Problematic: test edits':              '{{subst:Welcometest}}'
    'Welcome: Problematic: neutral point of view':   '{{subst:Welcomenpov}}'
    'Welcome: Problematic: conflict of interest':    '{{subst:Welcome-COI}}'
    'Welcome: Problematic: images / image links':    '{{subst:Welcome-image}}'

**Comment by ToBeFree** [comment]
Currently, it causes a chaotic, seemingly unsorted list to be displayed.

**Comment by ToBeFree** [comment]
https://phabricator.wikimedia.org/T192047

**Comment by benapetr** [comment]
Fixed
