### ISSUE TITLE
Setting to use months as headers in warning not working

### ISSUE THREAD

**Issue by papuass** [huggle/huggle3-qt-lx#284]
Setting "Use months as headers instead of the name of the page" (under Warnings tab) is not working — I can not disable it and value of this checkbox is not saved in user configuration page.

Using Huggle Version: 3.3.5 build: 3405 on lvwiki.

Sample edit with checkbox de-selected: https://lv.wikipedia.org/w/index.php?title=Dal%C4%ABbnieka_diskusija:159.148.153.221&oldid=2846416

**Comment by benapetr** [comment]
This fixes the problem with setting not being stored in config page https://github.com/huggle/huggle3-qt-lx/commit/2e5c5cd392af8335c9cd5f42ace0df5f6b4f0508

**Comment by benapetr** [comment]
TBH I am not really sure what was the original point of this option I think it was there to enforce using months even if the project configuration was set to use page name, but it probably doesn't work other way.

So if the project config use months as headers, you can't change it to use page name just by disabling this, it's probably necessary to change this in project config.

I don't really know what is a purpose of this override option though

**Comment by benapetr** [comment]
I think this was fixed
