### ISSUE TITLE
IRC not showing full user name

### ISSUE THREAD

**Issue by AbelmoschusEsculentus** [huggle/huggle3-qt-lx#292]
I tried the latest beta version of Huggle. A user is called "The Voidwalker", but the message showed "**The** did a rollback on enwiki of whatever whatever". I know some user names have >1 words and the first word is unique, but this time I think having the first word "The" in user names is not rare at all. Should we automatically substitute spaces of user names with underscores? It's a common practice though.
![screen shot 2018-06-18 at 10 00 05](https://user-images.githubusercontent.com/36526983/41515040-6fc03d0c-72de-11e8-81a3-b02e7f8591b2.png)

**Comment by benapetr** [comment]
I already fixed this but the problem is not on your side, but on side of user with space in name, they will have to download newer version of Huggle so that their nick is correct on IRC.
