### ISSUE TITLE
Edit form problems

### ISSUE THREAD

**Issue by AbelmoschusEsculentus** [huggle/huggle3-qt-lx#294]
1. I checked the minor edit button, but the edit is not marked as minor.
2. Times font is not so suitable for the preview. (from what I've seen)
3. Preview box is a bit small
4. Font size of preview box should be shrunk
5. Photos and media are not rendered in the preview (only the outline)
6. The "edit source" beside headings in the preview box is a bit annoying
7. Red links are not shown in the preview box
8. When I copy and paste formatted text to the edit box, the font size of the copied text will not be same as others.
Thanks for reading

**Comment by benapetr** [comment]
1: fixed
2: fixed
3: you can resize it
4:what is shunk?

6, 7 is probably something to be fixed on MW API level

8 fixed

**Comment by AbelmoschusEsculentus** [comment]
I am using Qt5.11.1 currently. The preview box of edit form and report user form is WAY too small.
![screen shot 2018-08-04 at 20 01 06](https://user-images.githubusercontent.com/36526983/43676305-287d06c4-9821-11e8-9550-eed242cb5ff6.png)
![screen shot 2018-08-04 at 20 00 54](https://user-images.githubusercontent.com/36526983/43676307-2996f222-9821-11e8-9ed1-12cd8c9aad2d.png)

**Comment by AbelmoschusEsculentus** [comment]
Still looking weird (only in Edit form, report form is ok)
[Demo.zip](https://github.com/huggle/huggle3-qt-lx/files/2260043/Demo.zip)

**Comment by benapetr** [comment]
it doesn't happen to me, no idea why, try if this helps: https://github.com/huggle/huggle3-qt-lx/commit/f434102fa664e324367ffd6e477d7e610c6e4c5e

Other thing that would definitely help is setting a constrain on max vsize but that could break this on HD displays as they would need way more pixels to display regular size font.

**Comment by AbelmoschusEsculentus** [comment]
Just tried your latest commit. Didn't work :(

**Comment by AbelmoschusEsculentus** [comment]
Oh I tried to use Qt5.10.1 and it's fixed.
