### ISSUE TITLE
multiple issues with the macOS integration

### ISSUE THREAD

**Issue by core-code** [huggle/huggle3-qt-lx#304]
you application does not have a 'Bundle Identifier', i.e. a ** CFBundleIdentifier**  entry in its ** Info.plist**  file.

all mac apps are supposed to have one, multiple things like caching and native preferences will be broken if you don't have a bundle identifier.

also, version information is missing. when selecting the app in the Finder, it doesn't display any version:  the **CFBundleVersion** and **CFShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by benapetr** [comment]
I did this but I think there is no difference, at least version info is still not visible https://github.com/huggle/huggle3-qt-lx/commit/e3c9e76cfab9e5391cdad4338d3a73e0f5e7b9c3

**Comment by core-code** [comment]
the info doesn't show up in the finder because, sorry, the key should read
CFBundleShortVersionString
and not
CFShortVersionString
