### ISSUE TITLE
Snap FTBFS

### ISSUE THREAD

**Issue by lfaraone** [huggle/huggle3-qt-lx#307]
https://build.snapcraft.io/user/huggle/huggle3-qt-lx/367169

```
DEPRECATED: The 'prepare' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn7 for more information.
Skipping pull desktop-qt5 (already ran)
Skipping pull application (already ran)
Skipping build desktop-qt5 (already ran)
Building application 
/bin/sh: 39: ./build/prepare_snap.sh: not found
Failed to run 'prepare': Exit code was 127.
```

Looks like there's a path issue?

**Comment by benapetr** [comment]
Yes, but I have no idea why it suddenly stopped working

The file is located in src/build/prepare_snap.sh

No idea what path should be in snapcraft.yml for it to work, the thing changes too quickly for me to keep pace

**Comment by benapetr** [comment]
Basically the reason for this script to exist is that older versions of snapcraft were not able to check out repository recursively, and this repo is full of submodules. Other thing it does is that it copies "definitions_prod.hpp" to definitions.hpp, which is step typically done by "configure" script, but in case you want to build huggle using CMake directly, without invoking configure script, you need to do that by hand.

```
#!/bin/sh

# Old git requires these commands to run from repo root
cd ../src || exit 1
echo "Preparing in `pwd`"
git submodule init
git submodule update
cd huggle_core || exit 1
sh update.sh
cp definitions_prod.hpp definitions.hpp || exit 1
```
