### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by AbelmoschusEsculentus** [huggle/huggle3-qt-lx#310]
Hi. I am using Qt 5.12.0 and macOS Mojave dark mode. I can barely see some of Huggle's darker icons (arrows at upper left corner, display talk, open diff in external browser) although I do not click them often. The contrast between the diff browser in the middle and black background hurts my eyes a lot after facing it for a while. Any solutions to this problem?

Screenshot: https://imgur.com/a/Tk2hG3C

**Comment by benapetr** [comment]
probably related to CSS style that is being used

if "background-color: white" was not there it would be dark, but so would be the text, some updates to CSS would be needed, when you browse internet in dark mode, are web pages also dark?

https://github.com/huggle/huggle3-qt-lx/blob/master/src/huggle_core/Resources/html/Header.html

Keep in mind that Huggle is a browser so this what you see in middle are actual HTML pages.

**Comment by AbelmoschusEsculentus** [comment]
No. The dark mode doesn't change anything inside the web browser

**Comment by AbelmoschusEsculentus** [comment]
I tried it but still the login form and everything except the diff browser are all black. They should be all white.
