### ISSUE TITLE
Everything is giant

### ISSUE THREAD

**Issue by Gestrid** [huggle/huggle3-qt-lx#318]
I just updated to 3.4.6 from 3.3.5, and now the whole UI is giant.  Is there any way to fix this?
<img width="389" alt="Annotation 2019-03-20 223813" src="https://user-images.githubusercontent.com/6199046/54730921-de008e00-4b61-11e9-9251-79c1109190be.png">

![image](https://user-images.githubusercontent.com/6199046/54730687-93cadd00-4b60-11e9-904f-912d23f5b031.png)
I made the history and user info box smaller before I took this screenshot.  It originally covered most of the welcome page.

![image](https://user-images.githubusercontent.com/6199046/54730977-14d6a400-4b62-11e9-9c65-65775ea8c1ff.png)
I can't save my preferences without tabbing to the save button.  This is the smallest height I could resize it to.

**Comment by benapetr** [comment]
Yes,

Latest Huggle has support for UDH screens unlike 3.3.5, so if you did workaround described on https://meta.wikimedia.org/wiki/Huggle/Download just undo it (the scaling performed by system thing)
