### ISSUE TITLE
Huggle crashes system in latest macOS Mojave

### ISSUE THREAD

**Issue by QEDK** [huggle/huggle3-qt-lx#320]
System details:
macOS Mojave 10.14.4
latest Huggle
All logs that I could retrieve at https://pastebin.com/VUvMc2e1

Steps:
* Run .dmg and move app to Applications. Then, run it with option+click. Opens correctly the first time.
* Quit app, run again. System crashes with lots of visual artifacts on the screen.
* Restart and app is running, works normally. Messes up again when you quit and rerun.
* Sometimes, it does not.

**Comment by benapetr** [comment]
crashes system? like whole OS?

I will check it

**Comment by benapetr** [comment]
I just downloaded 3.4.8 dmg on my work MacBook (Mojave), the package was compiled on my personal macbook that runs High Sierra. It works flawlessly to me.

**Comment by QEDK** [comment]
Unable to reproduce error. Closing for now.
