### ISSUE TITLE
Huggle forgets watchlist setting between sessions

### ISSUE THREAD

**Issue by creffett** [huggle/huggle3-qt-lx#328]
Huggle consistently loses my watchlisting settings between sessions.  I haven't investigated further to see whether other settings are lost, but this one definitely resets every time. Steps to reproduce:
1. Open settings window, go to Warnings tab
2. Change the "Preference for watchlist..." setting to "Follow your on-wiki preferences," click "OK" to save changes
3. Close Huggle completely
4. Re-open Huggle, go to settings -> warnings again, the watchlist setting will be back to "Add to watchlist"

Running this on latest Windows 10, can provide logs as needed.

**Comment by benapetr** [comment]
it works for me I think it was fixed but never released, new version is coming
