### ISSUE TITLE
random sizechange amount

### ISSUE THREAD

**Issue by papayaisnotafood** [huggle/huggle3-qt-lx#344]
It seems like that [摘要: /* 角色 */ Size change: "+23042”」
the number that I put Quotation mark are totally random, I use mac os 15, 3.4.10 build: 3880 3.4.10

**Comment by methecooldude** [comment]
What is the diff associated with this?

**Comment by benapetr** [comment]
I don't think it's random at all it's taken as diff between old and new edit size:

```
        if (element.attributes().contains("length_new")
               && element.attributes().contains("length_old"))
        {
            long size = element.attribute("length_new").toLong() - element.attribute("length_old").toLong();
            edit->SetSize(size);
        }
```

**Comment by papayaisnotafood** [comment]
but somtimes it just change a single word but shows a huge number.

**Comment by papayaisnotafood** [comment]
next time I see I will take a picture.
