### ISSUE TITLE
AIV reporting causes crash

### ISSUE THREAD

**Issue by NovemLinguae** [huggle/huggle3-qt-lx#354]
https://en.wikipedia.org/wiki/Wikipedia_talk:Huggle/Feedback#Crash_after_reporting_user

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/79697282/215642905-46f1fa3a-6627-49cb-bde5-cfa19c360ab1.png">

I haven't tried to reproduce this. I'm filing on behalf of the above users for increased visibility.

**Comment by blu3r4d0n** [comment]
I have been able to resolve this by running the latest commit. I am not sure which commit introduced the error.

**Comment by phuzion** [comment]
I've been testing the latest nightly for a few days, and it seems that [this commit](https://github.com/huggle/huggle3-qt-lx/commit/544f743176a292a476fcf71f11ddbfd4c2b9d498) has fixed the issue.

**Comment by NovemLinguae** [comment]
Nice. Sounds like we should do a release to get the fix into production.

**Comment by benapetr** [comment]
release done
