### ISSUE TITLE
Add Hebrew Wikipedia to whitelist service

### ISSUE THREAD

**Issue by abartov** [huggle/huggle3-qt-lx#366]
Hello.

I've noticed the whitelist mechanism isn't persisting for Hebrew Wikipedia. The Huggle client gives the following error:

```
Fri Jan 19 16:41:55 2024   ERROR: Failed to store data to white list: <br />
<b>Fatal error</b>:  Uncaught Exception: There is no such a wiki in /home/huggle/www/whitelist.php:149
Stack trace:
#0 /home/huggle/www/whitelist.php(179): Whitelist::get_wiki()
#1 /home/huggle/www/whitelist.php(267): Whitelist-&gt;save()
#2 /home/huggle/www/index.php(42): Whitelist-&gt;init()
#3 {main}
  thrown in <b>/home/huggle/www/whitelist.php</b> on line <b>149</b><br />
```

[This action](https://huggle.bena.rocks/?action=display&wp=he.wikipedia.org) also fails, with the same message.

I could not find where one is supposed to add he.wikipedia.org, unless it is in [this function](https://github.com/huggle/wl/blob/master/src/whitelist.php#L58).

Can anyone shed light on this?

**Comment by benapetr** [comment]
resolved
