### ISSUE TITLE
Build fails with HMUTEX_TYPE errors

### ISSUE THREAD

**Issue by abartov** [huggle/huggle3-qt-lx#373]
After pulling from the codebase and running **configure** and **make clean**, the build fails with multiple errors like this:

```
[ 24%] Building CXX object huggle_core/CMakeFiles/huggle_core.dir/collectable.cpp.o
/home/asaf/dev/huggle3-qt-lx/src/huggle_core/collectable.cpp:30:66: error: cannot convert ‘QMutex*’ to ‘HMUTEX_TYPE*’ in initialization
   30 | HMUTEX_TYPE* Collectable::WideLock = new QMutex(QMutex::Recursive);
      |                                                                  ^
/home/asaf/dev/huggle3-qt-lx/src/huggle_core/collectable.cpp: In constructor ‘Huggle::Collectable::Collectable()’:
/home/asaf/dev/huggle3-qt-lx/src/huggle_core/collectable.cpp:35:26: error: invalid use of incomplete type ‘class HMUTEX_TYPE’
```

**Comment by benapetr** [comment]
Hello, make sure you properly clean the build, especially auto-generated definitions.hpp (it should be taken from https://github.com/huggle/huggle3-qt-lx/blob/master/src/huggle_core/definitions_prod.hpp) this file contains the definition of missing type

**Comment by abartov** [comment]
As I wrote, I did **make clean**.  I now also tried completely removing the release directory and re-running configure and make. The result is exactly the same.

Is there something else I need to do to "properly clean the build"?
(I am building on Linux using g++ 13.2.0)

**Comment by benapetr** [comment]
yes, that is indeed not enough, this is unfortunate design I admit that :)

the definitions.hpp file is used as a "configuration file" for the build, similar to .config of Linux kernel, but more crude. Basically if it doesn't exist, configure script makes a copy of definitions_prod.hpp as definitions.hpp, but if it exists, it assumes you might have made some modifications and therefore doesn't touch it.

You will need to either copy definitions_prod.hpp over your copy of definitions.hpp (it's in src/huggle_core) or just delete definitions.hpp and run the configure script again, but result is probably going to be the same.

**Comment by abartov** [comment]
Ah, thank you, it builds fine now; I missed the difference between definitions and definitions_prod in your earlier response, I apologize.
